### ISSUE TITLE
Option to show time since start of the release

### ISSUE THREAD

**Issue by redcatbear** [exasol/release-droid#120]
# Situation

Waiting for a release to finish can make a user nervous. So it would be nice to have a kind of a stop-watch running that shows and updates the time since the release was started.

Updated text is only useful in interactive terminals, so it should be off by default.

## Acceptance Criteria

* Switch added to display time since release start
* When activated, the timer should be displayed and updated each second
* Optional: if possible it would be nice if the time of the last release build could be displayed as a reference (depending on whether the GH API supports that)
* Additional proposal by @kaklakariada: release-droid displays the link of the current workflow run in github to enable the user to visit the script directly

**Comment by ckunki** [comment]
[Github API](https://docs.github.com/en/rest/releases/releases) includes attributes "created_at" and  "updated_at".

Here is a sample for project spark-connector 
|tag | created_at | updated_at | &Delta; t [h:mm] 
|-----|-------|------|---------|
|1.1.0 | 04.06.2021 10:42 | 04.06.2021 11:26 | 00:44
|1.2.0 | 18.01.2022 11:28 | 18.01.2022 14:00 | 02:31

**Comment by ckunki** [comment]
https://stackoverflow.com/questions/4573123/java-updating-text-in-the-command-line-without-a-new-line

**Comment by ckunki** [comment]
Additional proposal: release-droid displays the link of the current workflow run in github to enable the user to visit the script directly

**Comment by ckunki** [comment]
Currently release-droid queries the status of the github action in intervals of 60 seconds.
@kaklakariada proposes to reduce interval to 15 seconds.
Additionally

**Comment by redcatbear** [comment]
Reducing to 15 is approved. I would keep some back-out though, if build runs 45 minutes, two minutes more are not a big deal. Its better to make the build faster.

**Comment by ckunki** [comment]
Color options:
## Option O1
* As long as release duration is within expectation
  * Elapsed time is green (= good) 
  * Remaining time is yellow (= neutral)
  * Display ETA
* As soon as the release takes longer than expected 
  * Elapsed time is yellow (= neutral) 
  * Overdue time is red (= bad)
  * Do not display ETA

![image](https://user-images.githubusercontent.com/81821845/183349217-c01f3837-ffc2-42b4-967f-912011462d66.png)

## Option O1a
* Like Option O1 but use white color for neutral parts

![image](https://user-images.githubusercontent.com/81821845/183349249-db078daf-cc96-45f8-8678-bdd1f9cf8950.png)

## Option O2
* Elapsed time is always yellow
* Remaining time within expectation is green
* Overdue time is red 

![image](https://user-images.githubusercontent.com/81821845/183349282-3e81bdf8-96c8-4966-aecd-7d808129352f.png)

## Option O2a
* Like Option O2 but use white color for elapsed time

![image](https://user-images.githubusercontent.com/81821845/183349306-f911a123-5489-4189-8800-54839a3c5185.png)

**Comment by ckunki** [comment]
### Output for a simulated release (coloring Option1)
As long as release duration is within expectation
* Display ETA
* Show elapsed parts in green
* Show expected remaining time in yellow
* Use progress bar to show elapsed and remaining duration in relation to expected total duration 

![image](https://user-images.githubusercontent.com/81821845/183349514-b6d46cb1-6132-46d3-b2db-c7f9f317891b.png)

As soon as the release takes longer than expected 
* Do not display ETA anymore
* Show elapsed parts in yellow
* Show excess duration in red 
* Use progress bar to show original estimation and excess duration in relation to actual total duration

![image](https://user-images.githubusercontent.com/81821845/183349538-354c5284-1ed0-42d8-ab86-a605f7408183.png)

**Comment by redcatbear** [comment]
Very nice mock-up. Can't wait to see the result in action.

**Comment by ckunki** [comment]
One question to @redcatbear, though:
Currently RD prints progress unconditionally and there are no options to suppress output.
Concluding from that and AFAIK RD is intended to be used only interactively.
Do we still need a separate option to activate progress output, though?
