### ISSUE TITLE
Remove duplication from ci-build and release_droid_prepare_original_checksum.yml workflows

### ISSUE THREAD

**Issue by jakobbraun** [exasol/release-droid#196]
Both the ci-build and the release_droid_prepare_original_checksum.yml GitHub Action workflows build the project and run all integration tests. That's a duplication in the configuration for the build.
Especially for projects with a more complicated CI setup like https://github.com/exasol/exasol-test-setup-abstraction-java/ thats a problem.

Idea:
Build the checksum in each CI build and grab it from there.

**Comment by jakobbraun** [comment]
Something seems to be strange here. I just ran the release of https://github.com/exasol/exasol-test-setup-abstraction-java/ and it did not user the `release_droid_prepare_original_checksum.yml` workflow.

**Comment by AnastasiiaSergienko** [comment]
@jakobbraun can you please show the logs of the run when the workflow wasn't used?

**Comment by jakobbraun** [comment]
@AnastasiiaSergienko sure. It just happened again with the release of project-keeper:
```
2021-09-15T08:39:07.715961

Goal: RELEASE
Repository: exasol/project-keeper-maven-plugin
Platforms: MAVEN, GITHUB

Validation is successful!

Validation succeeded. [MAVEN,GITHUB] Version format is correct.
Validation succeeded. [MAVEN,GITHUB] A new tag.
Validation succeeded. [MAVEN,GITHUB] 'changelog.md' file.
Validation succeeded. [MAVEN,GITHUB] 'changes_1.2.0.md' file.
Validation succeeded. [MAVEN,GITHUB] Release body in 'changes_1.2.0.md' file.
Validation succeeded. [MAVEN,GITHUB] Workflows for checksum generation exist.
Validation succeeded. [MAVEN,GITHUB] 'version' in the pom file exists.
Validation succeeded. [MAVEN,GITHUB] 'artifactId' in the pom file exists.
Validation succeeded. [MAVEN,GITHUB] Maven plugin 'project-keeper-maven-plugin'.
Validation succeeded. [MAVEN] Workflow for a Maven release.
Validation succeeded. [MAVEN] Project description presents in pom.xml file.
Validation succeeded. [MAVEN] Project URL presents in pom.xml file.
Validation succeeded. [GITHUB] Release letter header.
Validation succeeded. [GITHUB] Mentioned GitHub tickets.
Release is successful!

Release succeeded. [MAVEN,GITHUB] Release finished.
```

**Comment by AnastasiiaSergienko** [comment]
Thanks, I'll investigate it.

**Comment by pj-spoelders** [comment]
wouldn't the simplest way be to replace mvn verify with mvn package in these checksum workflows?

**Comment by jakobbraun** [comment]
The argumentation for having it there was: Building the jar could lead to a corrupted jar. The integration tests would detect this since they usually test the built jar.

**Comment by pj-spoelders** [comment]
don't you do that in the CI workflow already?

**Comment by jakobbraun** [comment]
yes. But for the release we build a new jar. It could be different. That's why we capture the checksum then and verify that for example the release on maven build creates the same checksum again.

**Comment by pj-spoelders** [comment]
After some discussion, TBD'd further when more people are in. I'll create a meeting request.

**Comment by pj-spoelders** [comment]
The main focus of this ticket is the refactoring of the CI steps to speed these up. Hence the refactoring instead of the bug tag (which seems resolved)
