### ISSUE TITLE
Use 'droid' consistently

### ISSUE THREAD

**Issue by redcatbear** [exasol/release-droid#197]
## Situation

Some artifacts (like the configuration files) still use the old name. Please change to `release-droid` uniformly.

**Comment by AnastasiiaSergienko** [comment]
It's a breaking change if we rename the config file. I've replaced 'robot' references in the tests for now.
The filename change should come together with a new major version

**Comment by AnastasiiaSergienko** [comment]
Actually, the config file was already renamed. So I can't see any other 'robot' references, I removed everything I found in the latest commit. So I'm closing this ticket.

Closed with #199
