### ISSUE TITLE
Validate credentials before using them

### ISSUE THREAD

**Issue by kaklakariada** [exasol/release-droid#201]
By accident I forgot to enter my credentials to `~/.release-droid/credentials`:

```
jira_username=
jira_password=
```
This lead to a failure when releasing to jira.

Before starting, release-droid should verify that non-empty credentials are available.

**Comment by AnastasiiaSergienko** [comment]
If you forget to add credentials, the release droid asks you to input them interactively via console. So this is intended not to check that jira_username/jira_password/etc in the file because not all of us want to keep credentials in the file.
