### ISSUE TITLE
Add support for Go projects

### ISSUE THREAD

**Issue by kaklakariada** [exasol/release-droid#220]
Release droid must
* Support language `go`
* Identify Go projects based on the `go.mod` file
* Use prefix `v` for the version number and tags

**Comment by ckunki** [comment]
Hello @kaklakariada: Is this issue still relevant? 
See tickets 
* #248 
* #245 
* #237

**Comment by kaklakariada** [comment]
No. RD must create tags with `v` prefix as described in https://github.com/exasol/release-droid/issues/257.
But this should be the only required change to support Go.

**Comment by ckunki** [comment]
Duplicates #257
