### ISSUE TITLE
Prepend version (tag) to Github release title

### ISSUE THREAD

**Issue by tomuben** [exasol/release-droid#229]
## Background

Our internal policy states that a Github release title should start with the version number.
Thus, it would be nice if release-droid already could create the release title of Github releases in the correct format. Currently, release-droid just copies the code name found in the changelog.
It should be technically simple to prepend the version to the title, as the version is already known (release-droid knows which tag to create).

## Acceptance Criteria

New Github release drafts, created by release-droid, already should have the version as prefix in the release title.

**Comment by ckunki** [comment]
Will change `GitHubReleaseMaker.createReleaseModel`
