### ISSUE TITLE
Always validate before releasing

### ISSUE THREAD

**Issue by jakobbraun** [exasol/release-droid#240]
I just waited 10 mins for a release and then rd failed with a wrong release date error. 

Suggestion : Run such quick validations before the release.

**Comment by ckunki** [comment]
Release date can be verified by running 
```
java -jar release-droid-*.jar -n $(basename $(pwd)) --local . --goal validate 
```
Sample output 
```
2023-02-02 15:59:35.080 [INFO   ] Validation started.
2023-02-02 15:59:41.109 [SEVERE ] VALIDATION FAILED!
E-RD-GH-31: Release date 2023-02-01 in file 'changes_1.5.0.md' has past already. Please make sure to release on the same
 date as specified. [For platforms: GITHUB]
```

**Comment by ckunki** [comment]
Proposal:
* Keep support for options `--local . --goal validate` like before 
* Change semantics of `--goal release` to do 
  * (1) `--goal validate` (i.e. *remotely*, not *local*)
  * (2) `--goal release` (as of before implementation of this ticket)
