### ISSUE TITLE
Release sha256sum checksum together with the asset

### ISSUE THREAD

**Issue by morazow** [exasol/release-droid#30]
## Situation

As a user of RR, I want to release `sha256sum` of the the asset together with asset.

This should help the users of the asset to ensure that their download (or upload to remote services such as BucketFS) is successfully.

## Acceptance Criteria

- The checksum.sha256.txt is uploaded to the assets of release 
- The text file should contain the `sha256sum` of the asset

**Comment by redcatbear** [comment]
Actually the standard procedure would be to create one checksum file per asset and upload that. The start with the same prefix, but one has a suffix indicating the used hash algorithm.

**Comment by redcatbear** [comment]
For a concrete example of why this is important, check:
https://community.exasol.com/t5/discussion-forum/issue-with-virtual-schema-and-jdbc-adapter/m-p/6209
