### ISSUE TITLE
Set logging level via property

### ISSUE THREAD

**Issue by redcatbear** [exasol/release-droid#38]
## Situation

The current document suggests changing the log level in the JDK. That is not ideal.
Instead create a local configuration file and set a property when starting the Java VM.

```
java -Djava.util.logging.config.file=<path to logging file> ...
```

**Comment by redcatbear** [comment]
It would also be a good idea to ship a proper example as resource with RR. You can take the file from the VS as a starting point. This also provides better default message rendering.

**Comment by AnastasiiaSergienko** [comment]
I think I tried this but didn't make it work so far. I'll try it again
