### ISSUE TITLE
Validate human-readable dependency list

### ISSUE THREAD

**Issue by redcatbear** [exasol/release-droid#4]
## Situation

Even though project using package management already have a clearly defined dependency list, those lists are optimized to be machine-readable.

It is a sign of recognition and good manors to properly attribute other projects from which we use libraries and plug-ins as external dependencies. That is why we list the dependencies prominently on the first page of the repository (in the `README.md` files).

Currently this is a manual process. Even if a team does this diligently, mistakes are bound to happen in manual synchronization between package list and `README.md`. This is why RR needs a validation step that ensures all external dependencies are properly listed and attributed.

## Acceptance Criteria

1. RR compares the package list and `README.md`
1. RR lists all discrepancies
1. RR stops the release process if there are discrepancies

**Comment by jakobbraun** [comment]
For Java this is sloved by [project-keeper](https://github.com/exasol/project-keeper-maven-plugin).
