### ISSUE TITLE
Allow specifying the platforms in the command line in a more standard way 

### ISSUE THREAD

**Issue by chiaradiamarcelo** [exasol/release-droid#92]
Currently for using the release droid from the console, the user needs to specify the platforms as a CSV argument as follows `-platform github,maven`.

It would be nice to have this in a more standard way to make it less error prone, as `-p github -p maven`

**Comment by redcatbear** [comment]
I think both are fine. In fact a lot of CLI parsers probably should be able to handle them identically.
